# Test suite config
[services.one]
name = "one" # must be the same as in line upper 
enabled = true 
command = "echo hi"
depends = []

[services.two]
name = "two"
enabled = true 
command = "echo hi2"
depends = ["one"]

[services.three]
name = "three"
enabled = false 
command = "echo hi3"
depends = []

# See:
# https://github.com/Freemorger/after
[services.four]
name = "four"
enabled = true 
command = "after 15s echo delayed1"
depends = ["two"]

# [services.five]
# name = "five"
# enabled = true 
# command = "after 20s echo delayed2"
# depends = ["two", "three"]

# [services.a]
# name = "a"
# enabled = true 
# command = "echo a"
# depends = ["b"]
#
# [services.b]
# command = "echo b"
# enabled = false 
# depends = ["a"]
