# Test suite config
[services.one]
command = "echo hi"
depends = []

[services.two]
command = "echo hi2"
depends = ["one"]

[services.three]
command = "echo hi3"
depends = []

# See:
# https://github.com/Freemorger/after
[services.four]
command = "after 20s echo delayed1"
depends = ["two", "three"]

[services.five]
command = "after 20s echo delayed2"
depends = ["two", "three"]

# [services.a]
# command = "echo a"
# depends = ["b"]
#
# [services.b]
# command = "echo b"
# depends = ["a"]
